### PR TITLE
Merge master jdk-20+31 into openj9-staging

### PR DESCRIPTION
**Pull request by JasonFengJ9**
Resolved the merging conflicts:
```
	src/java.base/share/classes/java/lang/Thread.java
	src/java.base/share/classes/java/lang/foreign/VaList.java
	src/java.base/share/classes/jdk/internal/foreign/CABI.java
	src/java.base/share/classes/jdk/internal/foreign/SystemLookup.java
	src/java.base/share/classes/jdk/internal/foreign/abi/SharedUtils.java
	src/java.base/share/classes/jdk/internal/foreign/abi/aarch64/CallArranger.java
	src/java.base/share/classes/jdk/internal/foreign/abi/x64/sysv/CallArranger.java
	src/java.base/share/classes/jdk/internal/foreign/abi/x64/windows/CallArranger.java
	test/jdk/java/foreign/CallGeneratorHelper.java
	test/jdk/java/foreign/NativeTestHelper.java
	test/jdk/java/foreign/TestClassLoaderFindNative.java
	test/jdk/java/foreign/TestStringEncoding.java
	test/jdk/java/foreign/TestVarArgs.java
	test/jdk/java/foreign/valist/VaListTest.java
```

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by JasonFengJ9** [comment]
@ChengJin01 as we discussed, this is a branch based on `openj9-staging` merged w/the latest OpenJDK 20. I have resolved some merging conflicts, but as expected, the compilation failed, pls create another branch to make changes along w/ OpenJ9 repo PR.

**Comment by ChengJin01** [comment]
@JasonFengJ9, could you help check the following errors detected by the compilation?  I will rebase your branch once you finish resolving these errors.

```
/.../openj9-openjdk-jdk20/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:400: error: cannot find symbol
		return mod.implIsEnableNativeAccess();
		          ^
  symbol:   method implIsEnableNativeAccess()
  location: variable mod of type Module
/.../openj9-openjdk-jdk20/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:404: error: cannot find symbol
		Module.implAddEnableNativeAccessAllUnnamed();
		      ^
  symbol:   method implAddEnableNativeAccessAllUnnamed()
  location: class Module
/.../openj9-openjdk-jdk20/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:454: error: cannot find symbol
		return Thread.extentLocalCache();
		             ^
  symbol:   method extentLocalCache()
  location: class Thread
/.../openj9-openjdk-jdk20/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:458: error: cannot find symbol
		Thread.setExtentLocalCache(cache);
		      ^
  symbol:   method setExtentLocalCache(Object[])
  location: class Thread
/.../openj9-openjdk-jdk20/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:462: error: cannot find symbol
		return Thread.extentLocalBindings();
		             ^
  symbol:   method extentLocalBindings()
  location: class Thread
/.../openj9-openjdk-jdk20/build/linux-x86_64-server-release/support/j9jcl/java.base/share/classes/java/lang/Access.java:466: error: cannot find symbol
		Thread.setExtentLocalBindings(bindings);
		      ^
  symbol:   method setExtentLocalBindings(Object)
...
```

**Comment by JasonFengJ9** [comment]
These are OpenJDK new additions, looking into it.

**Comment by JasonFengJ9** [comment]
@ChengJin01 you can cherry-pick https://github.com/eclipse-openj9/openj9/pull/16574 to fix those compilation errors https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/9#issuecomment-1396191559

**Comment by ChengJin01** [comment]
> @ChengJin01 you can cherry-pick [eclipse-openj9/openj9#16574](https://github.com/eclipse-openj9/openj9/pull/16574) to fix those compilation errors [#9 (comment)](https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/9#issuecomment-1396191559)

@JasonFengJ9, a bunch of `UnsatisfiedLinkError` were constantly captured in compilation:
```
Exception in thread "Common-Cleaner" java.lang.UnsatisfiedLinkError: java/lang/Thread.ensureMaterializedForStackWalk(Ljava/lang/Object;)V
	at java.base/java.lang.Thread.run(Thread.java:1639)
	at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
```
I am wondering whether this is something related to the Project Loom.

FYI: @fengxue-IS

**Comment by tajila** [comment]
FYI @babsingh

**Comment by JasonFengJ9** [comment]
> Exception in thread "Common-Cleaner" java.lang.UnsatisfiedLinkError: 
java/lang/Thread.ensureMaterializedForStackWalk(Ljava/lang/Object;)V

The native implementation is missing for this new native method, will see if a stub helps.

**Comment by babsingh** [comment]
re https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/9#issuecomment-1396413396:

It is related to JEP 429: Scoped Values (Incubator), https://openjdk.org/jeps/429.

**Comment by babsingh** [comment]
Stubs for the following functions are needed to resolve the linkage error:
```
JVM_EnsureMaterializedForStackWalk_func
JVM_FindScopedValueBindings
JVM_ScopedValueCache
JVM_SetScopedValueCache
```

**Comment by JasonFengJ9** [comment]
Added stub method at https://github.com/eclipse-openj9/openj9/pull/16574

@ChengJin01 your branch compiles w/ this change.
```
openjdk version "20-internal" 2023-03-21
OpenJDK Runtime Environment (build 20-internal-adhoc.jasonfeng.openj9-openjdk-jdk20)
Eclipse OpenJ9 VM (build ffi_disable_code_for_jep434_jdk20-514ca0435, JRE 20 Mac OS X aarch64-64-Bit 20230119_000000 (JIT enabled, AOT enabled)
OpenJ9   - 514ca0435
OMR      - 333650df1
JCL      - 32a6972f8e9 based on jdk-20+31)
```

**Comment by ChengJin01** [comment]
> Added stub method at [eclipse-openj9/openj9#16574](https://github.com/eclipse-openj9/openj9/pull/16574)
> @ChengJin01 your branch compiles w/ this change.
> 

I  pretty much resolved all compilation errors specific to FFI on my side by disabling all related code around but it needs to be verified on all supported platforms ensure the changes in OpenJ9 works good  in JDK17, 19, and 20+.

**Comment by ChengJin01** [comment]
PR for JDK20 is created at https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/12 plus the changes in OpenJ9 at https://github.com/eclipse-openj9/openj9/pull/16585 which are verified in JDK17, 19 & 20.

**Comment by pshipton** [comment]
@keithc-ca any concerns with this? Which will actually be merged via https://github.com/ibmruntimes/openj9-openjdk-jdk20/pull/12

**Comment by keithc-ca** [comment]
> @keithc-ca any concerns with this? Which will actually be merged via #12

Looking...

**Comment by keithc-ca** [comment]
Is there a good reason we're merging +31 instead of +32?

**Comment by pshipton** [comment]
> Is there a good reason we're merging +31 instead of +32?

It's where we started, we don't want to chase a moving target. Once we can merge +31, we can look at +32 or whatever is current. If nothing further is required to merge +32, we can just go through the normal acceptance.

**Comment by pshipton** [comment]
Like I said, this PR won't be merged, it's part of #12 which has this plus some additional changes. The goal is to merge #12 along with https://github.com/eclipse-openj9/openj9/pull/16585 to get to +31, and then look at getting more current, which should be easier.

**Comment by keithc-ca** [comment]
I'll make my comments in #12.

**Pull request merged**
