### PR TITLE
Cherry-pick missing changes from jdknext

### PR DESCRIPTION
**Pull request by keithc-ca**
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/532
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/533
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/530

### CODE REVIEW

**Comment by pshipton** [comment]
What do you want to run in a PR build? We can run any build manually.

**Comment by JasonFengJ9** [comment]
> What do you want to run in a PR build? We can run any build manually.

`sanity` on `xlinux` & `xlinuxcriu` can be  the starting point. I don't see any JDK20 personal builds, not sure if the framework underneath is ready.

**Comment by pshipton** [comment]
It's not hard to update. I've started https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/314/ and I'll check after lunch if there is any further problem that needs to be resolved. I can also update the internal job.

**Comment by JasonFengJ9** [comment]
```
11:26:01  RELEASES:'[20]'
[Pipeline] echo
11:26:01  PLATFORMS:'[x86-64_linux, x86-64_linux_criu]'
[Pipeline] echo
11:26:01  Warning: Selected Java versions (20) for x86-64_linux is not supported(nothing to do)!
[Pipeline] echo
11:26:01  Warning: Selected Java versions (20) for x86-64_linux_criu is not supported(nothing to do)!
[Pipeline] error
[Pipeline] cleanWs
11:26:01  [WS-CLEANUP] Deleting project workspace...
11:26:01  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
11:26:01  [WS-CLEANUP] done
```

**Comment by pshipton** [comment]
See https://github.com/eclipse-openj9/openj9/pull/16516

**Comment by JasonFengJ9** [comment]
PR builds depending on this - https://github.com/eclipse-openj9/openj9/pull/16516
Will merge if those pass.

**Comment by pshipton** [comment]
The build was successful.

**Review by JasonFengJ9 — APPROVED** [review]
LGTM

**Pull request merged**
